[package]
name = "nodikv"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
anyhow = "1.0.104"
futures-util = "0.3.34"
rustls = "0.23.45"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.30.0", features = ["rustls-tls-native-roots"] }
tokio-stream = { version = "0.1", features = ["net", "io-util"] }
